### ISSUE TITLE
menu icon not displaying

### ISSUE THREAD

**Issue by CollyneJumah** [koluochochieng/google-search-page#1]
menu on the right side not appearing

**Comment by koluochochieng** [comment]
This is done

**Comment by koluochochieng** [comment]
Worked on

**Comment by CollyneJumah** [comment]
Hi Kevin!
Trust all is well. This is with regard to the whatsapp conversation we had.
Below is the link to the JS guide.
https://docs.google.com/presentation/d/e/2PACX-1vQ-dk0cpOMaKn6s78_NeOxbsUEqHJmJOn3cvpB9haZnB0TNq6oDtRXckp2rXhywi3NC2bgXlJ3oHDUN/pub?start=false&loop=false&delayms=3000

Regards

**Comment by koluochochieng** [comment]
Thanks buddy well appreciated.

**Comment by CollyneJumah** [comment]
Kindly send me your email:: we chatting on github 😀😀
collynejumah2010@gmail.com
